-- ============================================
-- SEED SQL - Supermercado Node Data
-- Rodar no Supabase SQL Editor
-- ============================================
-- 1. Criar tabela de feedbacks
CREATE TABLE IF NOT EXISTS feedbacks (
    id bigint generated by default as identity primary key,
    sender text,
    name text,
    message text not null,
    timestamp timestamp with time zone default timezone('utc'::text, now()),
    category text,
    region text,
    urgency text,
    sentiment text,
    topic text,
    loja text default 'Matriz',
    status text default 'aberto',
    resolved_at text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 2. Criar tabela de config
DROP TABLE IF EXISTS config;
CREATE TABLE config (
    id bigint generated by default as identity primary key,
    type text not null,
    name text not null,
    color text,
    count int default 0,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 3. Criar tabela de produtos
CREATE TABLE IF NOT EXISTS produtos (
    id bigint generated by default as identity primary key,
    nome text not null,
    categoria text,
    preco numeric(10, 2) not null,
    preco_promo numeric(10, 2),
    em_estoque boolean default true,
    loja text default 'Matriz',
    unidade text default 'un',
    data_atualizacao timestamp with time zone default timezone('utc'::text, now()),
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 4. Criar tabela de lista de espera
CREATE TABLE IF NOT EXISTS lista_espera (
    id bigint generated by default as identity primary key,
    sender text not null,
    name text,
    produto_nome text not null,
    produto_id bigint references produtos(id),
    loja text default 'Matriz',
    notificado boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 5. Criar tabela de notificações opt-in
CREATE TABLE IF NOT EXISTS notificacoes (
    id bigint generated by default as identity primary key,
    sender text not null,
    name text,
    tipo text not null,
    -- 'ofertas', 'receita'
    ativo boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 6. Inserir Categorias de Supermercado
INSERT INTO config (type, name, color)
VALUES ('category', 'Atendimento', '#3b82f6'),
    ('category', 'Fila', '#f59e0b'),
    ('category', 'Hortifrúti', '#10b981'),
    ('category', 'Padaria', '#f97316'),
    ('category', 'Açougue', '#ef4444'),
    ('category', 'Limpeza', '#8b5cf6'),
    ('category', 'Preço', '#ec4899'),
    ('category', 'Promoção', '#14b8a6'),
    ('category', 'Estacionamento', '#6366f1');
-- 7. Inserir Lojas (pode expandir conforme a rede)
INSERT INTO config (type, name)
VALUES ('region', 'Matriz'),
    ('region', 'Filial Centro'),
    ('region', 'Filial Norte'),
    ('region', 'Filial Sul');
-- 8. Inserir placeholders de promoções
INSERT INTO config (type, name)
VALUES ('promotion_day', ''),
    ('promotion_week', '');
-- 9. Habilitar RLS (Row Level Security)
ALTER TABLE feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE config ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE lista_espera ENABLE ROW LEVEL SECURITY;
ALTER TABLE notificacoes ENABLE ROW LEVEL SECURITY;
-- 10. Criar políticas de acesso público (para anon key)
CREATE POLICY "Allow public read feedbacks" ON feedbacks FOR
SELECT USING (true);
CREATE POLICY "Allow public insert feedbacks" ON feedbacks FOR
INSERT WITH CHECK (true);
CREATE POLICY "Allow public update feedbacks" ON feedbacks FOR
UPDATE USING (true);
CREATE POLICY "Allow public read config" ON config FOR
SELECT USING (true);
CREATE POLICY "Allow public insert config" ON config FOR
INSERT WITH CHECK (true);
CREATE POLICY "Allow public update config" ON config FOR
UPDATE USING (true);
CREATE POLICY "Allow public delete config" ON config FOR DELETE USING (true);
CREATE POLICY "Allow public read produtos" ON produtos FOR
SELECT USING (true);
CREATE POLICY "Allow public insert produtos" ON produtos FOR
INSERT WITH CHECK (true);
CREATE POLICY "Allow public update produtos" ON produtos FOR
UPDATE USING (true);
CREATE POLICY "Allow public read lista_espera" ON lista_espera FOR
SELECT USING (true);
CREATE POLICY "Allow public insert lista_espera" ON lista_espera FOR
INSERT WITH CHECK (true);
CREATE POLICY "Allow public update lista_espera" ON lista_espera FOR
UPDATE USING (true);
CREATE POLICY "Allow public read notificacoes" ON notificacoes FOR
SELECT USING (true);
CREATE POLICY "Allow public insert notificacoes" ON notificacoes FOR
INSERT WITH CHECK (true);
CREATE POLICY "Allow public update notificacoes" ON notificacoes FOR
UPDATE USING (true);
